# Generated by Django 4.2.20 on 2025-04-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_files_mails_usertab'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usertab',
            new_name='employees',
        ),
    ]
